"""initial

Revision ID: d17bf05f79c0
Revises: 
Create Date: 2023-05-11 18:12:54.740066

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd17bf05f79c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guide_commentary', 'guide_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('guide_commentary', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guide_commentary', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('guide_commentary', 'guide_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
