# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 399)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 541, 331))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(440)
        self.verticalSlider = QtWidgets.QSlider(Dialog)
        self.verticalSlider.setGeometry(QtCore.QRect(540, 0, 24, 321))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(160, 350, 103, 36))
        self.saveButton.setObjectName("saveButton")
        self.quitButton = QtWidgets.QPushButton(Dialog)
        self.quitButton.setGeometry(QtCore.QRect(300, 350, 103, 36))
        self.quitButton.setObjectName("quitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "name"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "hero"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "rating"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "description"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "main_text"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "commetaries"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "data"))
        self.saveButton.setText(_translate("Dialog", "SAVE"))
        self.quitButton.setText(_translate("Dialog", "QUIT"))
