# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_qt/guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(845, 474)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Unbounded")
        self.user_name_label.setFont(font)
        self.user_name_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.user_name_label.setObjectName("user_name_label")
        self.verticalLayout.addWidget(self.user_name_label)
        self.guide_table = QtWidgets.QTableWidget(Dialog)
        self.guide_table.setMinimumSize(QtCore.QSize(823, 389))
        font = QtGui.QFont()
        font.setFamily("Unbounded Medium")
        font.setPointSize(12)
        self.guide_table.setFont(font)
        self.guide_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.guide_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.guide_table.setShowGrid(True)
        self.guide_table.setRowCount(0)
        self.guide_table.setObjectName("guide_table")
        self.guide_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.guide_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.guide_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.guide_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.guide_table.setHorizontalHeaderItem(3, item)
        self.guide_table.horizontalHeader().setCascadingSectionResizes(True)
        self.guide_table.horizontalHeader().setMinimumSectionSize(96)
        self.guide_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.guide_table)
        self.create_guide_bottom = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Unbounded SemiBold")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.create_guide_bottom.setFont(font)
        self.create_guide_bottom.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.create_guide_bottom.setObjectName("create_guide_bottom")
        self.verticalLayout.addWidget(self.create_guide_bottom)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.user_name_label.setText(_translate("Dialog", "user"))
        self.guide_table.setSortingEnabled(True)
        item = self.guide_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.guide_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Hero"))
        item = self.guide_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Descripton"))
        item = self.guide_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Rating"))
        self.create_guide_bottom.setText(_translate("Dialog", "Create guide"))
